name: build action
on: [push, pull_request]
jobs:
  build-cmake:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        compiler: [g++, clang++]
        build_type: [Debug, Release]
    steps:
      - name: clone
        id: checkout
        uses: actions/checkout@v4
      - name: install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
      - name: build
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=${{matrix.compiler}}
          cmake --build build
